
const actions = {
    TRENDING_API_REQUESTED_SUCCESS : 'TRENDING_API_REQUESTED_SUCCESS',
    TRENDING_API_REQUESTED_FAILURE : 'TRENDING_API_REQUESTED_FAILURE',
    TRENDING_API_REQUESTED : 'TRENDING_API_REQUESTED',
    FEATURED_API_REQUESTED_SUCCESS : 'FEATURED_API_REQUESTED_SUCCESS',
    FEATURED_API_REQUESTED_FAILURE : 'FEATURED_API_REQUESTED_FAILURE',
    FEATURED_API_REQUESTED : 'FEATURED_API_REQUESTED',
    SEARCH_API_REQUESTED_SUCCESS : 'SEARCH_API_REQUESTED_SUCCESS',
    SEARCH_API_REQUESTED_FAILURE : 'SEARCH_API_REQUESTED_FAILURE',
    SEARCH_API_REQUESTED : 'SEARCH_API_REQUESTED',
    SEARCH_STICKER_API_REQUESTED_SUCCESS : 'SEARCH_STICKER_API_REQUESTED_SUCCESS',
    SEARCH_STICKER_API_REQUESTED_FAILURE : 'SEARCH_STICKER_API_REQUESTED_FAILURE',
    SEARCH_STICKER_API_REQUESTED : 'SEARCH_STICKER_API_REQUESTED',
}

export default actions;